title: "Freya Tan"
description: "A simple site powered by Minimal Mistakes."
baseurl: "" # Leave this blank for user pages
url: "https://freya1919.github.io" # Your GitHub Pages URL

# Use the remote theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-include-cache


# Optional: Navigation defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
